//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onism.Cldr.Schema.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CldrSchemas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CldrSchemas() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Onism.Cldr.Schema.Resources.CldrSchemas", typeof(CldrSchemas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;rbnf&quot;: {
        ///    &quot;identity&quot;: {
        ///      &quot;version&quot;: {
        ///        &quot;number&quot;: &quot;STRING @revisionNumber&quot;,
        ///        &quot;cldrVersion&quot;: &quot;STRING @cldrVersion&quot;
        ///      },
        ///      &quot;language&quot;: &quot;STRING @language&quot;,
        ///      &quot;~territory&quot;: &quot;STRING @territory&quot;,
        ///      &quot;~script&quot;: &quot;STRING @script&quot;
        ///    },
        ///
        ///    &quot;rbnf&quot;: &quot;JOBJECT @dataObject&quot;
        ///  }
        ///}.
        /// </summary>
        internal static string Rbnf {
            get {
                return ResourceManager.GetString("Rbnf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;segments&quot;: {
        ///    &quot;identity&quot;: {
        ///      &quot;version&quot;: {
        ///        &quot;_number&quot;: &quot;STRING @revisionNumber&quot;,
        ///        &quot;_cldrVersion&quot;: &quot;STRING @cldrVersion&quot;
        ///      },
        ///
        ///      &quot;language&quot;: &quot;STRING @language&quot;,
        ///      &quot;~territory&quot;: &quot;STRING @territory&quot;,
        ///      &quot;~script&quot;: &quot;STRING @script&quot;,
        ///      &quot;~variant&quot;: &quot;STRING @variant&quot;
        ///    },
        ///
        ///    &quot;segmentations&quot;: &quot;JOBJECT @dataObject&quot;
        ///}
        ///.
        /// </summary>
        internal static string Segments {
            get {
                return ResourceManager.GetString("Segments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;main&quot;: {
        ///    &quot;@code&quot;: {
        ///      &quot;identity&quot;: {
        ///        &quot;version&quot;: {
        ///          &quot;_number&quot;: &quot;STRING @revisionNumber&quot;,
        ///          &quot;_cldrVersion&quot;: &quot;STRING @cldrVersion&quot;
        ///        },
        ///
        ///        &quot;~language&quot;: &quot;STRING @language&quot;,
        ///        &quot;~territory&quot;: &quot;STRING @territory&quot;,
        ///        &quot;~script&quot;: &quot;STRING @script&quot;,
        ///        &quot;~variant&quot;: &quot;STRING @variant&quot;
        ///      },
        ///
        ///      &quot;@dataName&quot;: &quot;JOBJECT @dataObject&quot;
        ///    }
        ///  }
        ///}.
        /// </summary>
        internal static string Standard {
            get {
                return ResourceManager.GetString("Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;supplemental&quot;: {
        ///    &quot;version&quot;: {
        ///      &quot;_number&quot;: &quot;STRING @revisionNumber&quot;,
        ///      &quot;_unicodeVersion&quot;: &quot;STRING @unicodeVersion&quot;,
        ///      &quot;_cldrVersion&quot;: &quot;STRING @cldrVersion&quot;
        ///    },
        ///
        ///    &quot;@dataName&quot;: &quot;JOBJECT @dataObject&quot;
        ///  }
        ///}.
        /// </summary>
        internal static string Supplemental {
            get {
                return ResourceManager.GetString("Supplemental", resourceCulture);
            }
        }
    }
}
