//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onism.Cldr.Test.Schema.Resources.Schemas {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class JsonSchemas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JsonSchemas() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Onism.Cldr.Test.Schema.Resources.Schemas.JsonSchemas", typeof(JsonSchemas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;1&quot;: &quot;STRING @text1&quot;,
        ///  &quot;2&quot;: &quot;STRING @text2&quot;,
        ///  &quot;~3&quot;: {
        ///    &quot;3.1&quot;: &quot;STRING @text3.1&quot;,
        ///    &quot;~@3.2&quot;: &quot;STRING @text3.2&quot;,
        ///    &quot;3.3&quot;: &quot;STRING @text3.3&quot;
        ///  },
        ///  &quot;@4&quot;: {
        ///    &quot;@4.1&quot;: &quot;STRING @text4.1&quot;,
        ///    &quot;~4.2&quot;: {
        ///      &quot;4.2.1&quot;: {
        ///        &quot;~@4.2.1.1&quot;: &quot;STRING @text4.2.1.1&quot;,
        ///        &quot;4.2.1.2&quot;: &quot;STRING @text4.2.1.2&quot;,
        ///        &quot;4.2.1.3&quot;: &quot;JOBJECT @object4.2.1.3&quot;
        ///      }
        ///    },
        ///    &quot;4.3&quot;: &quot;STRING @text4.3&quot;
        ///  },
        ///  &quot;~5&quot;: &quot;STRING @text5&quot;,
        ///  &quot;~6&quot;: {
        ///    &quot;6.1&quot;: {
        ///      &quot;6.1.1&quot;: {
        ///        &quot;~6.1.1.1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Diversified {
            get {
                return ResourceManager.GetString("Diversified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;~@1&quot;: {
        ///    &quot;~@1.1&quot;: {
        ///      &quot;~@1.1.1&quot;: {
        ///        &quot;~@1.1.1.1&quot;: {
        ///          &quot;~@1.1.1.1.1&quot;: {
        ///            &quot;~@1.1.1.1.1.1&quot;: {
        ///              &quot;~@1.1.1.1.1.1.1&quot;: {
        ///                &quot;~@1.1.1.1.1.1.1.1&quot;: {
        ///                  &quot;~@1.1.1.1.1.1.1.1.1&quot;: {
        ///                    &quot;~@1.1.1.1.1.1.1.1.1.1&quot;: {
        ///                      &quot;~@1.1.1.1.1.1.1.1.1.1.1&quot;: &quot;JOBJECT @object1.1.1.1.1.1.1.1.1.1&quot;
        ///                    }
        ///                  },
        ///                }
        ///              }
        ///            }
        ///          }
        ///        }
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NestedWithAllOptionalAndVariable {
            get {
                return ResourceManager.GetString("NestedWithAllOptionalAndVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;1&quot;: {
        ///    &quot;1.1&quot;: {
        ///      &quot;1.1.1&quot;: {
        ///        &quot;1.1.1.1&quot;: &quot;STRING @text1.1.1.1&quot;,
        ///        &quot;1.1.1.2&quot;: &quot;STRING @text1.1.1.2&quot;,
        ///        &quot;1.1.1.3&quot;: &quot;STRING @text1.1.1.3&quot;
        ///      },
        ///      &quot;1.1.2&quot;: {
        ///        &quot;1.1.2.1&quot;: &quot;STRING @text1.1.2.1&quot;,
        ///        &quot;1.1.2.2&quot;: &quot;STRING @text1.1.2.2&quot;,
        ///        &quot;1.1.2.3&quot;: &quot;STRING @text1.1.2.3&quot;
        ///      },
        ///      &quot;1.1.3&quot;: {
        ///        &quot;1.1.3.1&quot;: &quot;STRING @text1.1.3.1&quot;,
        ///        &quot;1.1.3.2&quot;: &quot;STRING @text1.1.3.2&quot;,
        ///        &quot;1.1.3.3&quot;: &quot;STRING @text1.1.3.3&quot;
        ///      }
        ///    },
        ///    &quot;1.2&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RequiredOnly {
            get {
                return ResourceManager.GetString("RequiredOnly", resourceCulture);
            }
        }
    }
}
