//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Onism.Cldr.Test.Schema.Resources.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocaleList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocaleList() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Onism.Cldr.Test.Schema.Resources.Locales.LocaleList", typeof(LocaleList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to af
        ///af-NA
        ///agq
        ///ak
        ///am
        ///ar
        ///ar-AE
        ///ar-BH
        ///ar-DJ
        ///ar-DZ
        ///ar-EG
        ///ar-EH
        ///ar-ER
        ///ar-IL
        ///ar-IQ
        ///ar-JO
        ///ar-KM
        ///ar-KW
        ///ar-LB
        ///ar-LY
        ///ar-MA
        ///ar-MR
        ///ar-OM
        ///ar-PS
        ///ar-QA
        ///ar-SA
        ///ar-SD
        ///ar-SO
        ///ar-SS
        ///ar-SY
        ///ar-TD
        ///ar-TN
        ///ar-YE
        ///as
        ///asa
        ///ast
        ///az
        ///az-Cyrl
        ///az-Latn
        ///bas
        ///be
        ///bem
        ///bez
        ///bg
        ///bm
        ///bn
        ///bn-IN
        ///bo
        ///bo-IN
        ///br
        ///brx
        ///bs
        ///bs-Cyrl
        ///bs-Latn
        ///ca
        ///ca-AD
        ///ca-ES-VALENCIA
        ///ca-FR
        ///ca-IT
        ///ce
        ///cgg
        ///chr
        ///ckb
        ///ckb-IR
        ///cs
        ///cu
        ///cy
        ///da
        ///da-GL
        ///dav
        ///de
        ///de-AT
        ///de-BE
        ///de-CH
        ///de-LI
        ///de-LU
        ///dje
        ///dsb
        ///dua
        ///dyo
        ///dz
        ///ebu
        ///ee
        ///ee-TG
        ///el
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Full {
            get {
                return ResourceManager.GetString("Full", resourceCulture);
            }
        }
    }
}
